import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Navbar2 from '../components/Navbar2'
import IndexBody  from 'components/IndexBody'
import Footer from 'components/Footer'

export default function Home() {
  return (
    <div className='Home'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500&family=Teko:wght@400;500;600;700&display=swap" rel="stylesheet"/>
      </Head>
      <Navbar showRight={true} crosser={true}/>
      <IndexBody/>
      <Footer />
    </div>
  )
}
